name: combine dependabot prs

on:
  schedule:
    # run every Friday at 00:42 UTC
    - cron: '42 0 * * 5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@e2dee3c2a03a8f9a0ecd82fb53cb852cdc7a2fb3
        with:
          pr_title: 🤖 Combined Dependabot PRs
